services:
  postgres:
    image: ankane/pgvector
    container_name: makima-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    restart: always
  pgvector:
    image: ankane/pgvector
    container_name: makima-pgvector
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
    volumes:
      - ./data/pgvector:/var/lib/postgresql/data
    restart: always
